"""
Aristotle — 10 skills × 5 tools × 1 rule.

铁律：AI 不能写 dict.md 和 decisions/。所有产出进 drafts/，等人 merge。
"""

import os
import re
import subprocess
from datetime import datetime
from pathlib import Path

# ── 常量 ──────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent
DICT_PATH = BASE_DIR / "dict.md"
DECISIONS_DIR = BASE_DIR / "decisions"
DRAFTS_DIR = BASE_DIR / "drafts"
BLOCKED = {"dict.md", "decisions/"}          # 唯一铁律

# 确保 drafts/ 存在
DRAFTS_DIR.mkdir(exist_ok=True)


def _guard(path: str) -> None:
    """draft-writer 的安全检查。"""
    for p in BLOCKED:
        if p in path:
            raise PermissionError(f"AI 不能写 {p} — 只能写 drafts/")


# ═══════════════════════════════════════════════════════════════════
# Tools（5 个）— Skills 不直接碰文件系统，通过 Tools 操作
# ═══════════════════════════════════════════════════════════════════

def dict_reader() -> str:
    """读取 dict.md，返回全文。"""
    if not DICT_PATH.exists():
        return ""
    return DICT_PATH.read_text(encoding="utf-8")


def decision_reader() -> list[tuple[str, str]]:
    """读取 decisions/ 下所有 .md，返回 [(filename, content), ...]。"""
    files = sorted(DECISIONS_DIR.glob("*.md")) if DECISIONS_DIR.exists() else []
    return [(f.name, f.read_text(encoding="utf-8")) for f in files]


def draft_writer(filename: str, content: str) -> Path:
    """
    写入 drafts/*.md。唯一可写入口。
    文件名不需要带路径，自动放在 drafts/ 下。
    """
    if "/" in filename or "\\" in filename:
        raise ValueError("filename 不能包含路径分隔符")
    path = DRAFTS_DIR / filename
    _guard(str(path.relative_to(BASE_DIR)))
    path.write_text(content, encoding="utf-8")
    return path


def log_scanner(text: str, terms: list[str]) -> dict[str, list[str]]:
    """
    在文本中扫描术语使用实例。
    返回 {term: [包含该 term 的行, ...]}。
    """
    lines = text.splitlines()
    result = {}
    for term in terms:
        hits = [line for line in lines if re.search(rf"\b{re.escape(term)}\b", line, re.I)]
        if hits:
            result[term] = hits
    return result


def git_commit(message: str) -> str:
    """git add + git commit drafts/ 变更。"""
    try:
        subprocess.run(["git", "add", str(DRAFTS_DIR)], cwd=BASE_DIR, check=True)
        subprocess.run(
            ["git", "commit", "-m", message],
            cwd=BASE_DIR, check=True, capture_output=True, text=True,
        )
        return "committed"
    except subprocess.CalledProcessError as e:
        # 可能没有变更需要提交
        return f"nothing to commit or error: {e.stderr.strip()}"


# ═══════════════════════════════════════════════════════════════════
# Campaign Mode（7 个 Skills）
# ═══════════════════════════════════════════════════════════════════

def define(term: str, context: str, status: str = "draft") -> Path:
    """
    为一个无定义的新词写草案。
    输出: drafts/define-<term>.md
    """
    slug = re.sub(r"[^\w\-]+", "-", term.lower()).strip("-")
    content = f"""# define: {term}

- **Definition**: （待填写）基于以下上下文提炼：
  {context.replace(chr(10), chr(10) + '  ')}
- **Status**: {status}
- **Notes**:

---
> Generated by Aristotle.define at {datetime.now().isoformat()}
"""
    return draft_writer(f"define-{slug}.md", content)


def fork(term: str, usage_a: str, usage_b: str) -> Path:
    """
    发现同一词被用作两个意思时，写 fork 草案。
    输出: drafts/fork-<term>.md
    """
    slug = re.sub(r"[^\w\-]+", "-", term.lower()).strip("-")
    content = f"""# fork: {term}

发现该词存在两种实际用法，待解决。

## 用法 A
{usage_a}

## 用法 B
{usage_b}

## 建议
（待讨论：是拆成两个词，还是保留一词多义并标注场景？）

---
> Generated by Aristotle.fork at {datetime.now().isoformat()}
"""
    return draft_writer(f"fork-{slug}.md", content)


def resolve(fork_draft_name: str, conclusion: str) -> Path:
    """
    对一个 fork draft 给出解决结论。
    输出: drafts/resolve-<term>.md
    """
    # 从 fork draft 文件名提取 term
    base = fork_draft_name.replace("fork-", "").replace(".md", "")
    content = f"""# resolve: {base}

基于 fork 讨论结论：

{conclusion}

## 后续动作
- [ ] 人审阅后 merge 进 dict.md
- [ ] 如产生新术语，调用 define 补充

---
> Generated by Aristotle.resolve at {datetime.now().isoformat()}
"""
    return draft_writer(f"resolve-{base}.md", content)


def align(term: str, misusage: str, correct: str = "") -> Path:
    """
    发现某 Bee 用错词时，写对齐草案。
    输出: drafts/align-<term>.md
    """
    slug = re.sub(r"[^\w\-]+", "-", term.lower()).strip("-")
    content = f"""# align: {term}

## 误用实例
{misusage}

## 正确用法
{correct or "（待补充 dict.md 中的定义）"}

## 建议
（待讨论：是纠正用法，还是接受新用法并更新定义？）

---
> Generated by Aristotle.align at {datetime.now().isoformat()}
"""
    return draft_writer(f"align-{slug}.md", content)


def decide(topic: str, conclusion: str, decision_id: int = 0) -> Path:
    """
    对争议拍板后，记录决策草案。
    输出: drafts/decide-<NNNN>-<slug>.md
    """
    slug = re.sub(r"[^\w\-]+", "-", topic.lower()).strip("-")
    serial = f"{decision_id:04d}" if decision_id else "XXXX"
    content = f"""# Decision {serial}: {topic}

## 结论
{conclusion}

## 状态
- [ ] 人审阅后移入 decisions/{serial}-{slug}.md

---
> Generated by Aristotle.decide at {datetime.now().isoformat()}
"""
    return draft_writer(f"decide-{serial}-{slug}.md", content)


def grill(term: str, question: str) -> Path:
    """
    对一个术语定义进行追问，暴露不稳之处。
    输出: drafts/grill-<term>.md
    """
    slug = re.sub(r"[^\w\-]+", "-", term.lower()).strip("-")
    content = f"""# grill: {term}

## 追问
{question}

## 待回答
（待讨论：这个追问是否暴露了定义的漏洞？）

---
> Generated by Aristotle.grill at {datetime.now().isoformat()}
"""
    return draft_writer(f"grill-{slug}.md", content)


def relate(term_a: str, term_b: str, relation: str) -> str:
    """
    在 define draft 的 Notes 中标注两术语关系。
    由于只能写 drafts/，这里返回一段应追加到 Notes 的文本，
    由调用方自行写入对应的 define draft。
    """
    return f"See also: {term_b} — {relation}"


# ═══════════════════════════════════════════════════════════════════
# Research Mode（3 个 Skills）
# ═══════════════════════════════════════════════════════════════════

def drift_watch(text: str) -> Path:
    """
    扫描日志/对话，发现术语漂移。
    输出: drafts/drift-YYYY-MM-DD.md
    """
    # 先读 dict 提取术语列表
    dict_text = dict_reader()
    terms = re.findall(r"^## (.+)$", dict_text, re.M)
    hits = log_scanner(text, terms)

    date = datetime.now().strftime("%Y-%m-%d")
    lines = [f"# drift-watch: {date}\n", f"扫描到 {len(hits)} 个术语出现：\n"]
    for term, ctx in hits.items():
        lines.append(f"\n### {term}\n")
        for c in ctx[:5]:          # 最多列 5 条
            lines.append(f"- {c.strip()}")
    lines.append(f"\n---\n> Generated by Aristotle.drift_watch at {datetime.now().isoformat()}\n")

    return draft_writer(f"drift-{date}.md", "\n".join(lines))


def ammo_prep(topic: str, requester: str = "") -> Path:
    """
    为其他 Bee 准备术语弹药包。
    输出: drafts/ammo-<topic>.md（标 [DRAFT]）
    """
    slug = re.sub(r"[^\w\-]+", "-", topic.lower()).strip("-")
    dict_text = dict_reader()
    # 简单提取相关段落：包含 topic 的条目
    sections = []
    for block in dict_text.split("\n---\n"):
        if topic.lower() in block.lower():
            sections.append(block.strip())

    sep = "\n\n"
    content = f"""# [DRAFT] ammo: {topic}

> 请求方: {requester or "unknown"}
> 状态: DRAFT — 人审阅后删除 [DRAFT] 标记或丢弃

## 相关定义
{sep.join(sections) or "（未在 dict.md 中找到直接匹配，请人工补充）"}

---
> Generated by Aristotle.ammo_prep at {datetime.now().isoformat()}
"""
    return draft_writer(f"ammo-{slug}.md", content)


def audit_debt() -> Path:
    """
    批次收尾时清算草稿债务。
    输出: drafts/audit-YYYY-MM-DD.md
    """
    date = datetime.now().strftime("%Y-%m-%d")
    drafts = sorted(DRAFTS_DIR.glob("*.md"))

    lines = [f"# audit-debt: {date}\n", f"当前 drafts/ 共有 {len(drafts)} 个文件：\n"]
    for d in drafts:
        lines.append(f"- `{d.name}`")
    lines.append("\n## 建议")
    lines.append("- 标 `[DRAFT]` 的 ammo 文件：用后即焚或定期清理")
    lines.append("- define/fork/resolve/decide：等人 merge 后删除")
    lines.append(f"\n---\n> Generated by Aristotle.audit_debt at {datetime.now().isoformat()}\n")

    return draft_writer(f"audit-{date}.md", "\n".join(lines))


# ═══════════════════════════════════════════════════════════════════
# CLI 入口（可选）
# ═══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python aristotle.py <skill> [args...]")
        print("Skills:", " ".join([
            "define", "fork", "resolve", "align", "decide", "grill", "relate",
            "drift_watch", "ammo_prep", "audit_debt"
        ]))
        sys.exit(1)

    skill = sys.argv[1]
    args = sys.argv[2:]

    try:
        result = globals()[skill](*args)
        print(result)
        # 自动 commit
        print(git_commit(f"Aristotle: {skill}"))
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
